# Generated by Django 5.0 on 2024-02-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_category_company_categories'),
        ('services', '0002_service_photos_alter_category_icon_alter_service_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
