# Generated by Django 5.0 on 2024-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_thumbnail'),
        ('services', '0006_alter_service_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='companies_refused',
            field=models.ManyToManyField(blank=True, related_name='refused_services', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
