# Generated by Django 5.0 on 2024-02-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_budget_description_alter_budget_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='created_at',
        ),
    ]
