# Generated by Django 5.0 on 2024-02-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_thumbnail'),
        ('services', '0010_remove_budget_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
    ]
