# Generated by Django 5.0 on 2024-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_budget_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(default='aguardando orçamento', max_length=255),
        ),
    ]
