# Generated by Django 5.0 on 2024-02-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_budget_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='imagens',
        ),
        migrations.AddField(
            model_name='service',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='services_files/'),
        ),
    ]
