# Generated by Django 5.0 on 2024-02-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_budget_description_remove_service_imagens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='services_files'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nfe',
            field=models.FileField(blank=True, null=True, upload_to='services_files'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nfse',
            field=models.FileField(blank=True, null=True, upload_to='services_files'),
        ),
    ]
