# Generated by Django 5.0 on 2024-02-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_service_imagem_alter_service_nfe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
