# Generated by Django 5.0 on 2024-02-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_service_state_alter_service_status'),
        ('services', '0016_delete_files'),
    ]

    operations = [
    ]
