# Generated by Django 5.0 on 2024-02-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_merge_20240226_1827'),
        ('services', '0017_merge_20240226_2132'),
    ]

    operations = [
    ]
