# Generated by Django 5.0 on 2024-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_merge_20240227_0052'),
        ('services', '0018_merge_20240227_1333'),
    ]

    operations = [
    ]
