# Generated by Django 5.0 on 2024-02-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.AlterField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(max_length=255),
        ),
    ]
