# Generated by Django 5.0 on 2024-02-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='companies_logo_thumb'),
        ),
    ]
